/*
 * Copyright 2023 Humberto Gomes, José Lopes, José Matos
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file  query_type.c
 * @brief Implementation of methods in include/queries/query_type.h
 *
 * ### Examples
 * See [the header file's documentation](@ref query_type_examples).
 */

#include <stdlib.h>
#include <string.h>

#include "queries/query_type.h"

/**
 * @struct query_type
 * @brief  A query definition based on its behavior.
 *
 * @var query_type::type_number
 *     @brief A number that identifies this query type.
 * @var query_type::parse_arguments
 *     @brief Method that parses query arguments and generates ::query_instance::argument_data.
 * @var query_type::clone_arguments
 *     @brief Method that clones query arguments, generated by ::query_type::parse_arguments.
 * @var query_type::free_arguments
 *     @brief Method that frees data returned by ::query_type::parse_arguments.
 * @var query_type::generate_statistics
 *     @brief Method that generates statistical data for all queries of the same type.
 * @var query_type::free_statistics
 *     @brief Method that frees data generated by ::query_type::generate_statistics.
 * @var query_type::execute
 *     @brief Method that executes a single query.
 */
struct query_type {
    size_t type_number;

    query_type_parse_arguments_callback_t parse_arguments;
    query_type_clone_arguments_callback_t clone_arguments;
    query_type_free_arguments_callback_t  free_arguments;

    query_type_generate_statistics_callback_t generate_statistics;
    query_type_free_statistics_callback_t     free_statistics;

    query_type_execute_callback_t execute;
};

query_type_t *query_type_create(size_t                                    type_number,
                                query_type_parse_arguments_callback_t     parse_arguments,
                                query_type_clone_arguments_callback_t     clone_arguments,
                                query_type_free_arguments_callback_t      free_arguments,
                                query_type_generate_statistics_callback_t generate_statistics,
                                query_type_free_statistics_callback_t     free_statistics,
                                query_type_execute_callback_t             execute) {

    query_type_t *const query = malloc(sizeof(query_type_t));
    if (!query)
        return NULL;

    query->type_number         = type_number;
    query->parse_arguments     = parse_arguments;
    query->clone_arguments     = clone_arguments;
    query->free_arguments      = free_arguments;
    query->generate_statistics = generate_statistics;
    query->free_statistics     = free_statistics;
    query->execute             = execute;

    return query;
}

query_type_t *query_type_clone(const query_type_t *type) {
    query_type_t *const clone = malloc(sizeof(query_type_t));
    if (!clone)
        return NULL;

    memcpy(clone, type, sizeof(query_type_t));
    return clone;
}

size_t query_type_get_type_number(const query_type_t *type) {
    return type->type_number;
}

query_type_parse_arguments_callback_t
    query_type_get_parse_arguments_callback(const query_type_t *type) {

    return type->parse_arguments;
}

query_type_clone_arguments_callback_t
    query_type_get_clone_arguments_callback(const query_type_t *type) {

    return type->clone_arguments;
}

query_type_free_arguments_callback_t
    query_type_get_free_arguments_callback(const query_type_t *type) {

    return type->free_arguments;
}

query_type_generate_statistics_callback_t
    query_type_get_generate_statistics_callback(const query_type_t *type) {

    return type->generate_statistics;
}

query_type_free_statistics_callback_t
    query_type_get_free_statistics_callback(const query_type_t *type) {

    return type->free_statistics;
}

query_type_execute_callback_t query_type_get_execute_callback(const query_type_t *type) {
    return type->execute;
}

void query_type_free(query_type_t *query) {
    free(query);
}
